version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/mozi-server
hooks:
  # ApplicationStop:
  #   - location: scripts/application_stop.sh
  #     timeout: 300
  #     runas: ubuntu
  # BeforeInstall:
  #   - location: scripts/before_install.sh
  #     timeout: 300
  #     runas: ubuntu
  # ApplicationStart:
  #   - location: scripts/start.sh
  #     runas: ubuntu
