swagger: '2.0'
info:
  description: 'Mozi Server API.'
  version: '1.0.0'
  title: 'Mozi Server'
host: 'localhost:3001'
basePath: '/api/v1'
tags:
  - name: 'Todo'
    description: '할일'
schemes:
  - 'http'
paths:
  /todos:
    get:
      tags:
        - 'Todo'
      summary: '사용자의 모든 Todo를 가져옵니다.'
      description: ''
      operationId: 'addPet'
      responses:
        '200':
          description: '성공'
          examples:
            application/json:
              [
                {
                  'id': '178dcfbc-0123-4a18-bd91-1a3b74cef47f',
                  'title': 'Getting started',
                  'description': 'what was it?',
                  'done': false,
                  'alarmed': false,
                  'longitude': null,
                  'latitude': null,
                  'index': null,
                  'createdAt': '2022-09-24T03:44:51.000Z',
                  'updatedAt': '2022-09-24T03:44:51.000Z',
                  'deletedAt': null,
                  'ownerId': '2432241311',
                },
                {
                  'id': '7c8d247b-ec0e-48bf-8089-49e3fb0fe21c',
                  'title': 'remember the milk',
                  'description': 'buy now',
                  'done': false,
                  'alarmed': false,
                  'longitude': null,
                  'latitude': null,
                  'index': 2,
                  'createdAt': '2022-09-24T03:44:34.000Z',
                  'updatedAt': '2022-09-24T03:44:34.000Z',
                  'deletedAt': null,
                  'ownerId': '2432241311',
                },
                {
                  'id': 'b54cdffb-2711-406a-bcc2-74ec02dfd80f',
                  'title': 'All my base',
                  'description': 'are belong to you',
                  'done': false,
                  'alarmed': false,
                  'longitude': null,
                  'latitude': null,
                  'index': null,
                  'createdAt': '2022-09-24T03:45:31.000Z',
                  'updatedAt': '2022-09-24T03:45:31.000Z',
                  'deletedAt': null,
                  'ownerId': '2432241311',
                },
              ]
          schema:
            type: 'array'
            items:
              $ref: '#/definitions/TodoResponse'
    post:
      tags:
        - 'Todo'
      summary: 'Todo를 DB에 생성하고 생성한 Todo를 반환합니다.'
      parameters:
        - in: 'body'
          name: 'body'
          description: '생성할 Todo 데이터'
          required: true
          schema:
            properties:
              title:
                type: 'string'
              description:
                type: 'string'
              done:
                type: 'boolean'
              alarmed:
                type: 'boolean'
              longitude:
                type: 'number'
              latitude:
                type: 'number'
              index:
                type: 'number'
      responses:
        '201':
          examples:
            application/json:
              {
                'id': 'b54cdffb-2711-406a-bcc2-74ec02dfd80f',
                'ownerId': '2432241311',
                'title': 'All my base',
                'description': ' are belong to you',
                'done': false,
                'alarmed': false,
                'index': 1,
                'updatedAt': '2022-09-24T03:45:31.014Z',
                'createdAt': '2022-09-24T03:45:31.014Z',
              }
          schema:
            $ref: '#/definitions/TodoResponse'

  /todos/{id}:
    get:
      tags:
        - 'Todo'
      summary: 'Todo를 가져옵니다.'
      description: ''
      parameters:
        - name: 'id'
          in: 'path'
          description: 'Todo의 uuid'
          required: true
          type: 'string'
      responses:
        '200':
          examples:
            application/json:
              {
                'id': 'b54cdffb-2711-406a-bcc2-74ec02dfd80f',
                'ownerId': '2432241311',
                'title': 'All my base',
                'description': ' are belong to you',
                'done': false,
                'alarmed': false,
                'index': 1,
                'updatedAt': '2022-09-24T03:45:31.014Z',
                'createdAt': '2022-09-24T03:45:31.014Z',
              }
    delete:
      tags:
        - 'Todo'
      summary: '특정 Todo를 삭제합니다.'
      description: ''
      parameters:
        - name: 'id'
          in: 'path'
          description: 'uuid'
          required: true
          type: 'string'
      responses:
        '200':
          examples:
            application/json: 1
    patch:
      tags:
        - 'Todo'
      summary: '특정 Todo를 업데이트합니다.'
      description: ''
      parameters:
        - name: 'id'
          in: 'path'
          description: 'uuid'
          required: true
          type: 'string'
        - in: 'body'
          name: 'body'
          description: '업데이트할 Todo 필드'
          required: true
          schema:
            properties:
              title:
                type: 'string'
                example: 'All my base'
              description:
                type: 'string'
                example: 'are belong to you'
              done:
                type: 'boolean'
                example: false
              alarmed:
                type: 'boolean'
                example: false
              longitude:
                type: 'number'
                example: 127.0016985
              latitude:
                type: 'number'
                example: 37.5642135
              index:
                type: 'number'
                example: 1
      responses:
        '201':
          examples:
            application/json:
              {
                'id': 'b54cdffb-2711-406a-bcc2-74ec02dfd80f',
                'ownerId': '2432241311',
                'title': 'All my base',
                'description': ' are belong to you',
                'done': false,
                'alarmed': false,
                'longitude': 127.0016985,
                'latitude': 37.5642135,
                'index': 1,
                'updatedAt': '2022-09-24T03:45:31.014Z',
                'createdAt': '2022-09-24T03:45:31.014Z',
              }
  /location/nearby:
    post:
      tags:
        - 'location'
      summary: '현재 경위도와 주어진 키워드를 기준으로 장소를 검색해서 리스트로 반환합니다'
      description: ''
      parameters:
        - in: 'body'
          name: 'body'
          description: '경도, 위도, 키워드'
          required: true
          schema:
            properties:
              longitude:
                type: number
                example: 127.0016985
              latitude:
                type: number
                example: 37.5642135
              keyword:
                type: string
                example: '스타벅스'
      responses:
        '200':
          examples:
            application/json:
              [
                '스타벅스 더종로R점',
                '스타벅스 서울타워점',
                '스타벅스 서울역사점',
                '스타벅스 파미에파크R점',
                '스타벅스 관악서울대입구R점',
              ]
definitions:
  TodoResponse:
    type: 'object'
    properties:
      _id:
        type: 'string'
      title:
        type: 'string'
      done:
        type: 'boolean'
      description:
        type: 'string'
      createdAt:
        type: 'string'
